/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team4.quanliquanmicay.View.Dialogs;

import com.team4.quanliquanmicay.Controller.EmployeeController;
import com.team4.quanliquanmicay.DAO.RoleDAO;
import com.team4.quanliquanmicay.DAO.UserDAO;
import com.team4.quanliquanmicay.Entity.UserAccount;
import com.team4.quanliquanmicay.Entity.UserRole;
import com.team4.quanliquanmicay.Impl.RoleDAOImpl;
import com.team4.quanliquanmicay.Impl.UserDAOImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

/**
 *
 * @author HP
 */
public class NhanVienJDialog extends javax.swing.JFrame implements EmployeeController {

    /**
     * Creates new form NhanVienJDialog
     */
    private UserDAO userDAO;
    private RoleDAO roleDAO; // Thêm RoleDAO
    private Map<String, String> roleMap; // Cache role_id -> name_role
    
    public NhanVienJDialog() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Khởi tạo DAO
        this.userDAO = new UserDAOImpl();
        this.roleDAO = new RoleDAOImpl(); // Khởi tạo RoleDAO
        this.roleMap = new HashMap<>(); // Khởi tạo cache
        
        // Load roles và status từ DB
        loadRoles();
        
        // Load dữ liệu lên bảng khi khởi động
        fillToTable();
        
        // Thêm event listener cho bảng
        tableInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    edit(); // Tự động load dữ liệu và ảnh khi click
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGioiTinh = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdEmployee = new javax.swing.JTextField();
        txtNameEmployee = new javax.swing.JTextField();
        chkMale = new javax.swing.JCheckBox();
        chkFemale = new javax.swing.JCheckBox();
        txtPhoneNumber = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNameAccount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 2));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN FIVE C");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("TÊN ĐĂNG NHẬP : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("HỌ TÊN NHÂN VIÊN :");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("GIỚI TÍNH :");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("SỐ ĐIỆN THOẠI :");

        txtIdEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNameEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        groupGioiTinh.add(chkMale);
        chkMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkMale.setText("NAM");

        groupGioiTinh.add(chkFemale);
        chkFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkFemale.setText("NỮ");

        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("MÃ NHÂN VIÊN :");

        txtNameAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("MẬT KHẨU :");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setText("EMAIL :");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setText("TRẠNG THÁI :");

        cboStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setText("VAI TRÒ :");

        cboRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtNameEmployee)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(chkMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFemale))
                    .addComponent(txtIdEmployee)
                    .addComponent(txtPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtNameAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(cboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkMale)
                                    .addComponent(chkFemale)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("THÔNG TIN CÁ NHÂN");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 2));

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/delete.png"))); // NOI18N
        btnClear.setText("LÀM MỚI");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/icons8-delete-48.png"))); // NOI18N
        btnDelete.setText("XÓA ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/refresh.png"))); // NOI18N
        btnUpdate.setText("CẬP NHẬT");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/Add to basket.png"))); // NOI18N
        btnSave.setText("LƯU");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/icons8-exit-32.png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(16, 16, 16))
        );

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tài khoản", "Mật khẩu", "Họ và tên", "Giới tính", "SĐT", "Email", "Trạng thái", "Vai trò", "Ngày tạo"
            }
        ));
        jScrollPane1.setViewportView(tableInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(575, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(502, 502, 502))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(424, 424, 424))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JCheckBox chkFemale;
    private javax.swing.JCheckBox chkMale;
    private javax.swing.ButtonGroup groupGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tableInfo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdEmployee;
    private javax.swing.JTextField txtNameAccount;
    private javax.swing.JTextField txtNameEmployee;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void loadRoles() {
        try {
            // Load các vai trò từ database
            cboRole.removeAllItems();
            cboRole.addItem("Tất cả");
            
            List<UserRole> roles = roleDAO.findAll();
            for (UserRole role : roles) {
                // Cache role mapping
                roleMap.put(role.getRole_id(), role.getName_role());
                
                // Hiển thị trong ComboBox
                String displayText = role.getRole_id() + " - " + role.getName_role();
                cboRole.addItem(displayText);
            }
            
            // Load trạng thái
            cboStatus.removeAllItems();
            cboStatus.addItem("Tất cả");
            cboStatus.addItem("Hoạt động");
            cboStatus.addItem("Không hoạt động");
            
            // Thêm event listeners cho filter
            addFilterListeners();
            
            System.out.println("Đã load " + roles.size() + " roles từ database");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi load roles: " + e.getMessage());
            e.printStackTrace();
            loadRolesFallback();
        }
    }
    
    /**
     * Fallback method nếu không load được từ DB
     */
    private void loadRolesFallback() {
        // Fallback data
        roleMap.clear();
        roleMap.put("R001", "Manager");
        roleMap.put("R002", "Staff");
        
        cboRole.removeAllItems();
        cboRole.addItem("Tất cả");
        cboRole.addItem("R001 - Manager");
        cboRole.addItem("R002 - Staff");
        
        cboStatus.removeAllItems();
        cboStatus.addItem("Tất cả");
        cboStatus.addItem("Hoạt động");
        cboStatus.addItem("Không hoạt động");
        
        addFilterListeners();
    }

    /**
     * Thêm event listeners cho ComboBox để filter dữ liệu
     */
    private void addFilterListeners() {
        // Event listener cho cboStatus
        cboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterAndFillTable();
            }
        });
        
        // Event listener cho cboRole
        cboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterAndFillTable();
            }
        });
    }

    /**
     * Filter và fill dữ liệu theo Status và Role được chọn
     */
    private void filterAndFillTable() {
        // Xóa dữ liệu cũ trong bảng
        DefaultTableModel model = (DefaultTableModel) tableInfo.getModel();
        model.setRowCount(0);
        
        try {
            // Lấy điều kiện filter
            String selectedStatus = (String) cboStatus.getSelectedItem();
            String selectedRole = (String) cboRole.getSelectedItem();
            
            // Lấy danh sách nhân viên từ database
            List<UserAccount> employees = userDAO.findAll();
            
            // Filter theo điều kiện
            List<UserAccount> filteredEmployees = filterEmployees(employees, selectedStatus, selectedRole);
            
            // Đổ dữ liệu đã filter vào bảng
            for (UserAccount emp : filteredEmployees) {
                Object[] row = {
                    emp.getUser_id(),           // Mã nhân viên
                    emp.getUsername(),         // Tài khoản
                    emp.getPass(),         // Mật khẩu
                    emp.getFullName(),         // Họ và tên
                    emp.getGender() != null ? (emp.getGender() == 1 ? "Nam" : "Nữ") : "Không xác định",           // Giới tính: 1=Nam, 0=Nữ
                    emp.getPhone_number(),            // SĐT
                    emp.getEmail(),            // Email
                    emp.getIs_enabled() != null ? (emp.getIs_enabled() == 1 ? "Hoạt động" : "Không hoạt động") : "Không xác định", // Trạng thái
                    getRoleName(emp.getRole_id()),     // Vai trò - Hiển thị tên thay vì ID
                    emp.getCreated_date()       // Ngày tạo
                };
                model.addRow(row);
            }
            
            System.out.println("Đã filter và load " + filteredEmployees.size() + "/" + employees.size() + " nhân viên");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi filter dữ liệu: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Filter danh sách nhân viên theo Status và Role
     */
    private List<UserAccount> filterEmployees(List<UserAccount> employees, String selectedStatus, String selectedRole) {
        List<UserAccount> filtered = new ArrayList<>();
        
        for (UserAccount emp : employees) {
            boolean matchStatus = true;
            boolean matchRole = true;
            
            // Filter theo Status
            if (selectedStatus != null && !selectedStatus.equals("Tất cả")) {
                if (selectedStatus.equals("Hoạt động")) {
                    matchStatus = (emp.getIs_enabled() != null && emp.getIs_enabled() == 1);
                } else if (selectedStatus.equals("Không hoạt động")) {
                    matchStatus = (emp.getIs_enabled() != null && emp.getIs_enabled() == 0);
                }
            }
            
            // Filter theo Role - cần extract role_id từ display text
            if (selectedRole != null && !selectedRole.equals("Tất cả")) {
                String roleId = extractRoleId(selectedRole);
                matchRole = roleId.equals(emp.getRole_id());
            }
            
            // Chỉ thêm vào danh sách nếu thỏa mãn cả 2 điều kiện
            if (matchStatus && matchRole) {
                filtered.add(emp);
            }
        }
        
        return filtered;
    }
    
    /**
     * Extract role_id từ display text (VD: "R001 - Manager" -> "R001")
     */
    private String extractRoleId(String displayText) {
        if (displayText != null && displayText.contains(" - ")) {
            return displayText.split(" - ")[0];
        }
        return displayText; // Fallback
    }

    /**
     * Lấy tên vai trò từ cache (nhanh hơn)
     */
    private String getRoleName(String roleId) {
        if (roleId != null && roleMap.containsKey(roleId)) {
            return roleMap.get(roleId); // Manager, Staff
        }
        return "Không xác định";
    }

    @Override
    public void validateEmployee() {
    }

    @Override
    public void open() {
    }

    @Override
    public void setForm(UserAccount entity) {
        // Điền dữ liệu từ entity vào form
        if (entity != null) {
            txtIdEmployee.setText(entity.getUser_id());
            txtNameAccount.setText(entity.getUsername());
            txtPassword.setText(entity.getPass());
            txtNameEmployee.setText(entity.getFullName());
            
            // Xử lý giới tính
            if (entity.getGender() != null) {
                if (entity.getGender() == 1) {
                    chkMale.setSelected(true);  // Nam
                    chkFemale.setSelected(false);
                } else {
                    chkMale.setSelected(false);
                    chkFemale.setSelected(true);  // Nữ
                }
            } else {
                // Reset giới tính nếu null
                groupGioiTinh.clearSelection();
            }
            
            txtPhoneNumber.setText(entity.getPhone_number());
            txtEmail.setText(entity.getEmail());
            
            // KHÔNG thay đổi cboStatus và cboRole khi setForm
            // Chỉ hiển thị thông tin trong form, không ảnh hưởng đến filter
            
            // Hiển thị hình ảnh nếu có
            if (entity.getImage() != null && !entity.getImage().trim().isEmpty()) {
                // Gọi method load ảnh
                loadEmployeeImage(entity.getImage());
            } else {
                lblImage.setText("No Image");
                lblImage.setIcon(null);
            }
            
            // Hiển thị role name từ DB
            displayRoleInfo(entity.getRole_id());
        }
    }

    /**
     * Hiển thị thông tin role (chỉ để xem, không ảnh hưởng filter)
     */
    private void displayRoleInfo(String roleId) {
        try {
            if (roleId != null) {
                UserRole role = roleDAO.findById(roleId);
                if (role != null) {
                    // Hiển thị trong label hoặc text field chỉ đọc
                    System.out.println("Employee role: " + role.getRole_id() + " - " + role.getName_role());
                    // Có thể thêm label để hiển thị: lblRoleInfo.setText(role.getName_role());
                }
            }
        } catch (Exception e) {
            System.err.println("Lỗi load role info: " + e.getMessage());
        }
    }

    @Override
    public UserAccount getForm() {
        // Lấy dữ liệu từ form tạo thành entity
        UserAccount entity = new UserAccount();
        
        entity.setUser_id(txtIdEmployee.getText().trim());
        entity.setUsername(txtNameAccount.getText().trim());
        entity.setPass(txtPassword.getText().trim());
        entity.setFullName(txtNameEmployee.getText().trim());
        
        // Xử lý giới tính
        if (chkMale.isSelected()) {
            entity.setGender(1);  // Nam
        } else if (chkFemale.isSelected()) {
            entity.setGender(0);  // Nữ
        }
        
        entity.setPhone_number(txtPhoneNumber.getText().trim());
        entity.setEmail(txtEmail.getText().trim());
        
        // Lấy role_id từ ComboBox (extract từ display text)
        String selectedRole = (String) cboRole.getSelectedItem();
        if (selectedRole != null && !selectedRole.equals("Tất cả")) {
            entity.setRole_id(extractRoleId(selectedRole));
        }
        
        // Xử lý trạng thái từ ComboBox
        String selectedStatus = (String) cboStatus.getSelectedItem();
        if (selectedStatus != null) {
            if (selectedStatus.equals("Hoạt động")) {
                entity.setIs_enabled(1);
            } else if (selectedStatus.equals("Không hoạt động")) {
                entity.setIs_enabled(0);
            }
        }
        
        // Xử lý hình ảnh
        entity.setImage(lblImage.getText());
        
        // Ngày tạo mặc định
        entity.setCreated_date(new java.util.Date());
        
        return entity;
    }

    @Override
    public void fillToTable() {
        // Gọi filterAndFillTable với "Tất cả" cho cả Status và Role
        cboStatus.setSelectedItem("Tất cả");
        cboRole.setSelectedItem("Tất cả");
        filterAndFillTable();
    }

    @Override
    public void edit() {
        // Lấy dòng được chọn trong bảng
        int selectedRow = tableInfo.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy user_id từ cột đầu tiên
            String userId = (String) tableInfo.getValueAt(selectedRow, 0);
            
            // Tìm entity từ database
            UserAccount entity = userDAO.findById(userId);
            
            if (entity != null) {
                // DEBUG: In ra giá trị thực tế
                System.out.println("Selected Employee: " + entity.getUser_id() + 
                                 " - Gender: " + entity.getGender() + 
                                 " - Is_enabled: " + entity.getIs_enabled() +
                                 " - Image: " + entity.getImage());
                
                // Điền dữ liệu vào form (KHÔNG ảnh hưởng đến ComboBox filter)
                setForm(entity);
                
                // Cho phép chỉnh sửa
                setEditable(true);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin nhân viên!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa!");
        }
    }

    /**
     * Load và hiển thị ảnh nhân viên
     */
    private void loadEmployeeImage(String imageName) {
        try {
            if (imageName != null && !imageName.trim().isEmpty()) {
                // Đường dẫn ảnh trong resources hoặc thư mục cụ thể
                String imagePath = "/images/employees/" + imageName;
                
                // Thử load ảnh từ resources
                java.net.URL imageURL = getClass().getResource(imagePath);
                
                if (imageURL != null) {
                    ImageIcon imageIcon = new ImageIcon(imageURL);
                    
                    // Resize ảnh cho phù hợp với lblImage
                    Image image = imageIcon.getImage();
                    Image scaledImage = image.getScaledInstance(
                        lblImage.getWidth() > 0 ? lblImage.getWidth() : 116, 
                        lblImage.getHeight() > 0 ? lblImage.getHeight() : 167, 
                        Image.SCALE_SMOOTH
                    );
                    
                    lblImage.setIcon(new ImageIcon(scaledImage));
                    lblImage.setText(""); // Xóa text nếu có ảnh
                } else {
                    // Nếu không tìm thấy ảnh, hiển thị tên file
                    lblImage.setIcon(null);
                    lblImage.setText(imageName);
                }
            } else {
                // Không có ảnh
                lblImage.setIcon(null);
                lblImage.setText("No Image");
            }
        } catch (Exception e) {
            System.err.println("Lỗi load ảnh: " + e.getMessage());
            lblImage.setIcon(null);
            lblImage.setText("Error");
        }
    }

    @Override
    public void create() {
    }

    @Override
    public void update() {
    }

    @Override
    public void delete() {
    }

    @Override
    public void clear() {
        // Xóa toàn bộ dữ liệu trên form
        txtIdEmployee.setText("");
        txtNameAccount.setText("");
        txtPassword.setText("");
        txtNameEmployee.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
        
        // Reset giới tính
        groupGioiTinh.clearSelection();
        
        // KHÔNG reset cboStatus và cboRole khi clear form
        // Để giữ nguyên điều kiện filter hiện tại
        
        // Reset hình ảnh
        lblImage.setText("");
        lblImage.setIcon(null);
        
        // KHÔNG gọi fillToTable() để tránh làm mất filter hiện tại
    }

    /**
     * Method riêng để reset filter về "Tất cả"
     */
    public void resetFilter() {
        cboStatus.setSelectedItem("Tất cả");
        cboRole.setSelectedItem("Tất cả");
        filterAndFillTable();
    }

    @Override
    public void setEditable(boolean editable) {
        // Cho phép/không cho phép chỉnh sửa form
        txtIdEmployee.setEditable(!editable); // ID không được sửa
        txtNameAccount.setEditable(editable);
        txtPassword.setEditable(editable);
        txtNameEmployee.setEditable(editable);
        txtPhoneNumber.setEditable(editable);
        txtEmail.setEditable(editable);
        
        chkMale.setEnabled(editable);
        chkFemale.setEnabled(editable);
        cboStatus.setEnabled(editable);
        cboRole.setEnabled(editable);
    }

    @Override
    public void checkAll() {
    }

    @Override
    public void uncheckAll() {
    }

    @Override
    public void deleteCheckedItems() {
    }
}
