/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team4.quanliquanmicay.View.management;

import com.team4.quanliquanmicay.Controller.CategoryController;
import com.team4.quanliquanmicay.Entity.Category;
import com.team4.quanliquanmicay.Impl.CategoryDAOImpl;
import com.team4.quanliquanmicay.DAO.CategoryDAO;
import com.team4.quanliquanmicay.util.XTheme;
import com.team4.quanliquanmicay.util.XDialog;
import com.team4.quanliquanmicay.util.XValidation;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class CategoryManagement extends javax.swing.JFrame implements CategoryController{

    private CategoryDAO categoryDAO = new CategoryDAOImpl();

    /**
     * Creates new form DoanhThuJDialog
     */
    public CategoryManagement() {
        this.setUndecorated(true);
        XTheme.applyFullTheme();
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Tắt khả năng di chuyển cột và edit
        disableTableEditing();
    }
    
    /**
     * Tắt khả năng edit và di chuyển cột trong table
     */
    private void disableTableEditing() {
        // Tắt khả năng di chuyển cột
        tblCategories.getTableHeader().setReorderingAllowed(false);
        
        // Tắt khả năng edit
        tblCategories.setDefaultEditor(Object.class, null);
        
        // Vô hiệu hóa editor cho từng cột
        for (int i = 0; i < tblCategories.getColumnCount(); i++) {
            tblCategories.getColumnModel().getColumn(i).setCellEditor(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnabled = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCateId = new javax.swing.JTextField();
        txtCateName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        radActive = new javax.swing.JRadioButton();
        radInactive = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategories = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(134, 39, 43));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản Lí Loại Món");

        jPanel2.setBackground(new java.awt.Color(204, 164, 133));

        jPanel3.setBackground(new java.awt.Color(204, 164, 133));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã loại :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên loại :");

        txtCateId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCateId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCateIdActionPerformed(evt);
            }
        });

        txtCateName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(183, 165, 147));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm món");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(185, 163, 147));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Cập Nhật");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(185, 163, 147));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Làm mới");
        btnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trạng thái :");

        btnEnabled.add(radActive);
        radActive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radActive.setForeground(new java.awt.Color(204, 204, 204));
        radActive.setText("Hoạt động");

        radInactive.setBackground(new java.awt.Color(204, 164, 133));
        btnEnabled.add(radInactive);
        radInactive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radInactive.setForeground(new java.awt.Color(204, 204, 204));
        radInactive.setText("Ngừng hoạt động");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(radActive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radInactive))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCateName)
                                .addComponent(txtCateId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radActive)
                    .addComponent(radInactive))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        btnExit.setBackground(new java.awt.Color(183, 165, 147));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 204, 204));
        btnExit.setText("Thoát");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblCategories.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategories.getTableHeader().setResizingAllowed(false);
        tblCategories.getTableHeader().setReorderingAllowed(false);
        tblCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategories);
        if (tblCategories.getColumnModel().getColumnCount() > 0) {
            tblCategories.getColumnModel().getColumn(0).setResizable(false);
            tblCategories.getColumnModel().getColumn(1).setResizable(false);
            tblCategories.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        create();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCateIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCateIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCateIdActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        open();
    }//GEN-LAST:event_formWindowOpened

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Kiểm tra xem có dữ liệu trên form không
        String categoryId = txtCateId.getText().trim();
        String categoryName = txtCateName.getText().trim();
        
        if (!categoryId.isEmpty() || !categoryName.isEmpty()) {
            String message = "Bạn có dữ liệu chưa lưu trên form:\n\n" +
                           "• Mã loại: " + (categoryId.isEmpty() ? "(trống)" : categoryId) + "\n" +
                           "• Tên loại: " + (categoryName.isEmpty() ? "(trống)" : categoryName) + "\n" +
                           "• Trạng thái: " + (radActive.isSelected() ? "Hoạt động" : 
                                               radInactive.isSelected() ? "Ngừng hoạt động" : "(chưa chọn)") + "\n\n" +
                           "Bạn có muốn:\n" +
                           "• Hủy bỏ dữ liệu và thoát\n" +
                           "• Tiếp tục chỉnh sửa";
            
            String[] options = {"Hủy bỏ và thoát", "Tiếp tục chỉnh sửa"};
            String choice = XDialog.selection(message, "Xác nhận thoát", options);
            
            if ("Hủy bỏ và thoát".equals(choice)) {
                this.dispose();
            }
            // Nếu chọn "Tiếp tục chỉnh sửa" thì không làm gì cả
        } else {
            // Không có dữ liệu, thoát bình thường
            if (XDialog.confirm("Bạn có chắc chắn muốn thoát?", "Xác nhận thoát")) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriesMouseClicked
        edit();
    }//GEN-LAST:event_tblCategoriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup btnEnabled;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radActive;
    private javax.swing.JRadioButton radInactive;
    private javax.swing.JTable tblCategories;
    private javax.swing.JTextField txtCateId;
    private javax.swing.JTextField txtCateName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        fillToTable();
    }

    @Override
    public void setForm(Category entity) {
        txtCateId.setText(entity.getCategory_id());
        txtCateName.setText(entity.getCategory_name());
        if (entity.getIs_available() == 1) {
            radActive.setSelected(true);
            radInactive.setSelected(false);
        } else {
            radActive.setSelected(false);
            radInactive.setSelected(true);
        }
    }

    @Override
    public Category getForm() {
        Category category = new Category();
        category.setCategory_id(txtCateId.getText());
        category.setCategory_name(txtCateName.getText());
        if (radActive.isSelected()) {
            category.setIs_available(1);
        } else {
            category.setIs_available(0);
        }
        return category;
    }

    @Override
    public void fillToTable() {
        List<Category> categories = categoryDAO.findAll();
        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
            categories.stream().map(category -> new Object[] {
                category.getCategory_id(),
                category.getCategory_name(),
                category.getIs_available() == 1 ? "Hoạt động" : "Ngừng hoạt động"
            }).toArray(Object[][]::new),
            new String[] { "Mã loại", "Tên loại", "Trạng thái" }
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false; // Không cho phép edit bất kỳ cột nào
            }
        });
        
        // Áp dụng lại cấu hình tắt edit sau khi set model
        disableTableEditing();
    }

    @Override
    public void edit() {
        int selectedRow = tblCategories.getSelectedRow();
        if (selectedRow >= 0) {
            String categoryId = tblCategories.getValueAt(selectedRow, 0).toString();
            String categoryName = tblCategories.getValueAt(selectedRow, 1).toString();
            String status = tblCategories.getValueAt(selectedRow, 2).toString();
            int isAvailable = status.equals("Hoạt động") ? 1 : 0;
            Category category = new Category(categoryId, categoryName, isAvailable);
            System.out.println("[SELECT] Chọn dòng: " + category);
            setForm(category);
            setEditable(true);
            txtCateId.setEditable(false); // Disable mã loại khi chọn dòng
            btnUpdate.setEnabled(true);
            btnReset.setEnabled(true);
            btnExit.setEnabled(true);
        }
    }

    /**
     * Tạo chuỗi thông tin để hiển thị trong dialog
     */
    private String formatCategoryInfo(Category category) {
        return String.format("Mã loại: %s\nTên loại: %s\nTrạng thái: %s", 
            category.getCategory_id(), 
            category.getCategory_name(), 
            category.getIs_available() == 1 ? "Hoạt động" : "Ngừng hoạt động");
    }
    
    @Override
    public void create() {
        try {
            // Validate form data
            String validationError = validateFormData();
            if (validationError != null) {
                XDialog.error(validationError, "Lỗi dữ liệu");
                return;
            }
            
            Category category = getForm();
            
            // Kiểm tra category name đã tồn tại chưa
            List<Category> existingCategories = categoryDAO.findAll();
            boolean nameExists = existingCategories.stream()
                .anyMatch(c -> c.getCategory_name().equalsIgnoreCase(category.getCategory_name()));
            
            if (nameExists) {
                XDialog.warning("Tên danh mục đã tồn tại!", "Cảnh báo");
                return;
            }
            
            // Hiển thị dialog xác nhận thêm
            boolean confirm = XDialog.confirm(
                "Bạn có chắc chắn muốn thêm danh mục '" + category.getCategory_name() + "'?", 
                "Xác nhận thêm"
            );
            
            if (confirm) {
                categoryDAO.create(category);
                XDialog.success("Thêm danh mục thành công!", "Thành công");
                clear();
                fillToTable();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.error("Lỗi khi thêm danh mục: " + e.getMessage(), "Lỗi hệ thống");
        }
    }

    @Override
    public void update() {
        try {
            // Validate form data
            String validationError = validateFormData();
            if (validationError != null) {
                XDialog.error(validationError, "Lỗi dữ liệu");
                return;
            }
            
            Category category = getForm();
            
            // Kiểm tra category name đã tồn tại chưa (trừ chính nó)
            List<Category> existingCategories = categoryDAO.findAll();
            boolean nameExists = existingCategories.stream()
                .anyMatch(c -> c.getCategory_name().equalsIgnoreCase(category.getCategory_name()) 
                    && !c.getCategory_id().equals(category.getCategory_id()));
            
            if (nameExists) {
                XDialog.warning("Tên danh mục đã tồn tại!", "Cảnh báo");
                return;
            }
            
            // Hiển thị dialog xác nhận cập nhật
            boolean confirm = XDialog.confirm(
                "Bạn có chắc chắn muốn cập nhật danh mục '" + category.getCategory_name() + "'?", 
                "Xác nhận cập nhật"
            );
            
            if (confirm) {
                categoryDAO.update(category);
                XDialog.success("Cập nhật danh mục thành công!", "Thành công");
                clear();
                fillToTable();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.error("Lỗi khi cập nhật danh mục: " + e.getMessage(), "Lỗi hệ thống");
        }
    }

    @Override
    public void delete() {
        try {
            Category category = getForm();
            if (category == null || XValidation.isEmpty(category.getCategory_id())) {
                XDialog.error("Vui lòng chọn danh mục cần xóa!", "Lỗi");
                return;
            }
            
            // Hiển thị dialog xác nhận xóa
            boolean confirm = XDialog.confirm(
                "Bạn có chắc chắn muốn xóa danh mục '" + category.getCategory_name() + "'?\n" +
                "Hành động này không thể hoàn tác!", 
                "Xác nhận xóa"
            );
            
            if (confirm) {
                categoryDAO.deleteById(category.getCategory_id());
                XDialog.success("Xóa danh mục thành công!", "Thành công");
                clear();
                fillToTable();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.error("Lỗi khi xóa danh mục: " + e.getMessage(), "Lỗi hệ thống");
        }
    }

    @Override
    public void clear() {
        // Làm mới form mà không hiển thị thông báo
        txtCateId.setText("");
        txtCateName.setText("");
        radActive.setSelected(true);
        txtCateId.setEditable(true);
        tblCategories.clearSelection();
    }

    @Override
    public void setEditable(boolean editable) {
        txtCateId.setEditable(!editable);
        txtCateName.setEditable(editable);
        radActive.setEnabled(editable);
        radInactive.setEnabled(editable);

        btnAdd.setEnabled(editable);
        btnUpdate.setEnabled(editable);
        btnReset.setEnabled(editable);
        btnExit.setEnabled(editable);
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String validateFormData() {
        Category category = getForm();
        
        if (XValidation.isEmpty(category.getCategory_id())) {
            return "Vui lòng nhập mã danh mục!";
        }
        
        if (XValidation.isEmpty(category.getCategory_name())) {
            return "Vui lòng nhập tên danh mục!";
        }
        
        if (category.getCategory_name().length() < 2) {
            return "Tên danh mục phải có ít nhất 2 ký tự!";
        }
        
        if (category.getCategory_name().length() > 50) {
            return "Tên danh mục không được quá 50 ký tự!";
        }
        
        return null; // Không có lỗi
    }
}
