/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team4.quanliquanmicay.View.management;

import com.team4.quanliquanmicay.Controller.TableController;
import com.team4.quanliquanmicay.DAO.TableForCustomerDAO;
import com.team4.quanliquanmicay.Entity.TableForCustomer;
import com.team4.quanliquanmicay.Impl.TableForCustomerDAOImpl;
import com.team4.quanliquanmicay.util.XTheme;
import com.team4.quanliquanmicay.util.XDialog;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.border.LineBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author HP
 */
public class TableManagement extends javax.swing.JFrame implements TableController {

    /**
     * Creates new form BanJDialog
     */
    public TableManagement() {
        this.setUndecorated(true);
        XTheme.applyFullTheme();
        initComponents();
        this.setLocationRelativeTo(null); 
        this.tableDAO = new TableForCustomerDAOImpl();
        pnlNormalTable.setLayout(new java.awt.GridLayout(2, 6, 15, 15)); // 3 hàng 4 cột
        pnlVipTable.setLayout(new java.awt.GridLayout(2, 6, 15, 15));    // 2 hàng 6 cột
        jTabbedPane1.setSelectedIndex(0); // Luôn hiển thị tab Normal Table trước
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlTable = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlNormalTable = new javax.swing.JPanel();
        pnlVipTable = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTable_Number = new javax.swing.JLabel();
        lblTable_Status = new javax.swing.JLabel();
        lblAmount1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        cboTable_Status = new javax.swing.JComboBox<>();
        txtTable_Number = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/refresh.png"))); // NOI18N
        jButton5.setText("THÊM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(134, 39, 43));

        lblTitle.setBackground(new java.awt.Color(102, 0, 0));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("QUẢN LÍ BÀN");

        jPanel2.setBackground(new java.awt.Color(204, 164, 133));

        pnlTable.setBackground(new java.awt.Color(204, 164, 133));

        jTabbedPane1.setBackground(new java.awt.Color(204, 164, 133));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnlNormalTable.setBackground(new java.awt.Color(255, 255, 255));
        pnlNormalTable.setPreferredSize(new java.awt.Dimension(1180, 479));
        pnlNormalTable.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlNormalTableLayout = new javax.swing.GroupLayout(pnlNormalTable);
        pnlNormalTable.setLayout(pnlNormalTableLayout);
        pnlNormalTableLayout.setHorizontalGroup(
            pnlNormalTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        pnlNormalTableLayout.setVerticalGroup(
            pnlNormalTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("1-12", pnlNormalTable);

        pnlVipTable.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlVipTableLayout = new javax.swing.GroupLayout(pnlVipTable);
        pnlVipTable.setLayout(pnlVipTableLayout);
        pnlVipTableLayout.setHorizontalGroup(
            pnlVipTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        pnlVipTableLayout.setVerticalGroup(
            pnlVipTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("13-24", pnlVipTable);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 164, 133));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblTable_Number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTable_Number.setForeground(new java.awt.Color(255, 255, 255));
        lblTable_Number.setText("BÀN SỐ :");

        lblTable_Status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTable_Status.setForeground(new java.awt.Color(255, 255, 255));
        lblTable_Status.setText("TRẠNG THÁI :");

        lblAmount1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAmount1.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount1.setText("SỐ CHỖ NGỒI :");

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboTable_Status.setEditable(true);
        cboTable_Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTable_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đang Phục Vụ", "Không hoạt động" }));

        txtTable_Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(183, 239, 197));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(30, 122, 30));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/add.png"))); // NOI18N
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 231, 153));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(122, 82, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/edit.png"))); // NOI18N
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(164, 216, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 102, 51));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/refresh.png"))); // NOI18N
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 179, 179));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/trash.png"))); // NOI18N
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(119, 50, 5));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/Exit.png"))); // NOI18N
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTable_Status)
                    .addComponent(lblTable_Number)
                    .addComponent(lblAmount1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboTable_Status, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTable_Number, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTable_Number)
                    .addComponent(txtTable_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTable_Status)
                    .addComponent(cboTable_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount1))
                .addGap(86, 86, 86))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(282, 282, 282))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Xóa bàn
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // Làm mới form
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Load bàn khi mở form
        loadTable();
        
        // Fill thông tin bàn đầu tiên lên form
        fillFirstTableToForm();
    }//GEN-LAST:event_formWindowOpened

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Thêm bàn mới
        create();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Cập nhật bàn
       this. update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboTable_Status;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblTable_Number;
    private javax.swing.JLabel lblTable_Status;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlNormalTable;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlVipTable;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtTable_Number;
    // End of variables declaration//GEN-END:variables

    private TableForCustomerDAO tableDAO;

    // Thêm biến này vào class TableManagement
    private JButton selectedButton = null;
    private int selectedTableNumber = -1;

    // Thêm phương thức mới để fill bàn đầu tiên lên form
    private void fillFirstTableToForm() {
        try {
            List<TableForCustomer> tables = tableDAO.findAll();
            if (tables != null && !tables.isEmpty()) {
                // Lấy bàn đầu tiên từ database
                TableForCustomer firstTable = tables.get(0);
                
                // Fill thông tin lên form
                setForm(firstTable);
                
                System.out.println("Đã fill thông tin bàn đầu tiên: Bàn số " + firstTable.getTable_number());
            } else {
                System.out.println("Không có bàn nào trong database");
            }
        } catch (Exception e) {
            System.err.println("Lỗi khi load bàn đầu tiên: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Cập nhật phương thức loadTable để không tự động tạo bàn mới
    private void loadTable() {
        List<TableForCustomer> tables = tableDAO.findAll();
        
        // Xóa tất cả bàn cũ trong panel
        pnlNormalTable.removeAll();
        pnlVipTable.removeAll();
        
        // Tạo map để tra cứu nhanh
        java.util.Map<Integer, TableForCustomer> tableMap = new java.util.HashMap<>();
        for (TableForCustomer t : tables) {
            tableMap.put(t.getTable_number(), t);
        }

        // 1-12: Normal
        for (int i = 1; i <= 12; i++) {
            TableForCustomer table = tableMap.get(i);
            pnlNormalTable.add(this.createButton(i, table));
        }

        // 13-24: VIP
        for (int i = 13; i <= 24; i++) {
            TableForCustomer table = tableMap.get(i);
            pnlVipTable.add(this.createButton(i, table));
        }
        
        // Cập nhật giao diện
        pnlNormalTable.revalidate();
        pnlNormalTable.repaint();
        pnlVipTable.revalidate();
        pnlVipTable.repaint();
    }

    // Thêm phương thức helper để tìm bàn theo số
    private TableForCustomer findTableByNumber(List<TableForCustomer> tables, int tableNumber) {
        for (TableForCustomer table : tables) {
            if (table.getTable_number() == tableNumber) {
                return table;
            }
        }
        return null;
    }

    // Thêm phương thức kiểm tra bàn tồn tại
    private boolean isTableExists(int tableNumber) {
        try {
            TableForCustomer table = tableDAO.findById(tableNumber);
            return table != null;
        } catch (Exception e) {
            return false;
        }
    }

    // Hàm lấy màu đậm khi chọn
    private Color getSelectedColorByStatus(int status) {
        switch (status) {
            case 0: // Trống
                return Color.decode("#616161"); // Xám đậm hơn
            case 1: // Hoạt động
                return Color.decode("#186a3b"); // Xanh đậm hơn
            case 2: // Ngưng phục vụ
                return Color.decode("#757575"); // Xám đậm khi chọn
            default:
                return Color.GRAY;
        }
    }

    // Thêm vào class:
    private Color getHoverColorByStatus(int status) {
        switch (status) {
            case 0: return Color.decode("#616161"); // Xám đậm
            case 1: return Color.decode("#196f3d"); // Xanh đậm
            case 2: return Color.decode("#bdbdbd"); // Xám đậm hơn xám trắng
            default: return Color.GRAY;
        }
    }

    // Sửa lại createButton
    private JButton createButton(int tableNumber, TableForCustomer table) {
        JButton btnTable = new JButton();
        btnTable.setContentAreaFilled(false); // Tắt nền mặc định
        btnTable.setOpaque(true);             // Cho phép vẽ nền custom
        btnTable.setText(String.format("Bàn #%d", tableNumber));
        btnTable.setPreferredSize(new Dimension(120, 120));
        btnTable.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 22));

        btnTable.setOpaque(true);
        btnTable.setContentAreaFilled(true);
        btnTable.setBorderPainted(false);
        btnTable.setFocusPainted(false);
        btnTable.setRolloverEnabled(false); // Tắt rollover mặc định

        final int buttonStatus = (table != null) ? table.getStatus() : -1;

        if (table == null) {
            btnTable.setEnabled(false);
            btnTable.setBackground(new Color(120, 144, 156));
        } else {
            btnTable.setEnabled(true);
            btnTable.setBorder(javax.swing.BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2));
            btnTable.setBorderPainted(true);
            if (tableNumber == selectedTableNumber) {
                btnTable.setBorder(new CompoundBorder(
                    new LineBorder(Color.PINK, 4, true),
                    new LineBorder(Color.LIGHT_GRAY, 2)
                ));
                btnTable.setBorderPainted(true);
                selectedButton = btnTable;
            } else {
                switch (buttonStatus) {
                    case 0: btnTable.setBackground(Color.decode("#bdbdbd")); break;
                    case 1: btnTable.setBackground(Color.decode("#27ae60")); break;
                    case 2: btnTable.setBackground(Color.decode("#f5f5f5")); break;
                    default: btnTable.setBackground(new Color(55, 71, 79));
                }
            }
            btnTable.setActionCommand(String.valueOf(table.getTable_number()));
            btnTable.addActionListener((ActionEvent e) -> {
                int num = Integer.parseInt(e.getActionCommand());
                this.selectTable(num, btnTable);
            });

            btnTable.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    if (btnTable != selectedButton && btnTable.isEnabled()) {
                        btnTable.setBackground(getHoverColorByStatus(buttonStatus));
                        btnTable.repaint();
                    }
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    if (btnTable != selectedButton && btnTable.isEnabled()) {
                        switch (buttonStatus) {
                            case 0: btnTable.setBackground(Color.decode("#bdbdbd")); break;
                            case 1: btnTable.setBackground(Color.decode("#27ae60")); break;
                            case 2: btnTable.setBackground(Color.decode("#f5f5f5")); break;
                            default: btnTable.setBackground(new Color(55, 71, 79));
                        }
                        btnTable.repaint();
                    }
                }
                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    // Khi nhấn chuột, tạm thời đổi sang màu hồng
                    if (btnTable.isEnabled()) {
                        btnTable.setBackground(Color.decode("#ff69b4")); // Màu hồng
                        btnTable.repaint();
                    }
                }
                @Override
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    // Khi thả chuột, trả lại màu đúng
                    if (btnTable.isEnabled()) {
                        if (btnTable == selectedButton) {
                            // Nếu là button đã chọn, trả về màu "selected"
                            TableForCustomer table = tableDAO.findById(Integer.parseInt(btnTable.getActionCommand()));
                            if (table != null) {
                                btnTable.setBackground(getSelectedColorByStatus(table.getStatus()));
                            }
                        } else {
                            // Nếu không phải button đã chọn, trả về màu trạng thái bình thường
                            switch (buttonStatus) {
                                case 0: btnTable.setBackground(Color.decode("#bdbdbd")); break;
                                case 1: btnTable.setBackground(Color.decode("#27ae60")); break;
                                case 2: btnTable.setBackground(Color.decode("#f5f5f5")); break;
                                default: btnTable.setBackground(new Color(55, 71, 79));
                            }
                        }
                        btnTable.repaint();
                    }
                }
            });
        }
        return btnTable;
    }

    // Sửa lại selectTable
    private void selectTable(int tableNumber, JButton btnTable) {
        System.out.println("Đã chọn bàn số: " + tableNumber);

        // Đổi border và màu button cũ về mặc định
        if (selectedButton != null && selectedButton != btnTable) {
            selectedButton.setBorder(javax.swing.BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2));
            selectedButton.setBorderPainted(true);
            // Lấy lại trạng thái của button cũ để set lại màu nền
            TableForCustomer oldTable = tableDAO.findById(selectedTableNumber);
            if (oldTable != null) {
                switch (oldTable.getStatus()) {
                    case 0: selectedButton.setBackground(Color.decode("#bdbdbd")); break; // Xám nhạt
                    case 1: selectedButton.setBackground(Color.decode("#27ae60")); break; // Xanh lá
                    case 2: selectedButton.setBackground(Color.decode("#f5f5f5")); break; // Xám trắng
                    default: selectedButton.setBackground(new Color(55, 71, 79));
                }
            }
        }

        // Đặt border màu #00fe92 dày 4px cho button mới
        btnTable.setBorder(new CompoundBorder(
            new LineBorder(Color.decode("#00fe92"), 4, true),
            new LineBorder(Color.LIGHT_GRAY, 2)
        ));
        btnTable.setBorderPainted(true);

        // Đổi màu nền button được chọn thành màu đậm hơn theo status
        TableForCustomer table = tableDAO.findById(tableNumber);
        if (table != null) {
            btnTable.setBackground(getSelectedColorByStatus(table.getStatus()));
        }

        selectedButton = btnTable;
        selectedTableNumber = tableNumber;

        // Fill form
        if (table != null) {
            setForm(table);
        } else {
            System.err.println("Không tìm thấy bàn số " + tableNumber + " trong database!");
        }
    }

    @Override
    public void open() {
        loadTable();
        this.setVisible(true);
    }

    // Cập nhật phương thức convertStatusToInt để xử lý đầy đủ các trạng thái
    private int convertStatusToInt(String status) {
        switch (status) {
            case "Trống": return 0;
            case "Hoạt Động": return 1;
            case "Ngưng Phục Vụ": return 2;
            default: return 0;
        }
    }

    private String convertIntToStatus(int status) {
        switch (status) {
            case 0: return "Trống";
            case 1: return "Hoạt Động";

            case 2: return "Ngưng Phục Vụ";
            default: return "Trống";
        }
    }

    // Cập nhật phương thức setForm để chuyển đổi status
    @Override
    public void setForm(Object entity) {
        if (entity instanceof TableForCustomer) {
            TableForCustomer table = (TableForCustomer) entity;
            
            // Fill thông tin vào form bên trái (thông tin bàn hiện tại)
            txtTable_Number.setText(String.valueOf(table.getTable_number()));
            cboTable_Status.setSelectedItem(convertIntToStatus(table.getStatus()));
            
            // Fill thông tin vào form bên phải (form chỉnh sửa)
   
            txtAmount.setText(String.valueOf(table.getAmount()));

            
            System.out.println("Đã fill thông tin bàn số " + table.getTable_number() + " lên form");
        }
    }

    // Cập nhật phương thức getForm để chuyển đổi status
    @Override
    public Object getForm() {
        TableForCustomer table = new TableForCustomer();
        try {
            table.setTable_number(Integer.parseInt(txtTable_Number.getText()));
            table.setAmount(Integer.parseInt(txtAmount.getText()));
            String statusText = (String) cboTable_Status.getSelectedItem();
            table.setStatus(convertStatusToInt(statusText));
        } catch (NumberFormatException e) {
            System.err.println("Lỗi chuyển đổi dữ liệu: " + e.getMessage());
        }
        return table;
    }

    @Override
    public void fillToTable() {
        loadTable();
    }

    @Override
    public void edit() {
      
    }

    // Cập nhật phương thức create để không kiểm tra trùng lặp nữa
    @Override
    public void create() {
        // Lấy dữ liệu từ form
        String tableNumberStr = txtTable_Number.getText().trim();
        String amountStr = txtAmount.getText().trim();
        String statusText = (String) cboTable_Status.getSelectedItem();

        // Kiểm tra trống thông tin
        if (tableNumberStr.isEmpty() || amountStr.isEmpty() || statusText == null || statusText.trim().isEmpty()) {
            XDialog.alert("Vui lòng nhập đầy đủ thông tin bàn!");
            return;
        }

        int tableNumber, amount;
        try {
            tableNumber = Integer.parseInt(tableNumberStr);
            amount = Integer.parseInt(amountStr);
        } catch (NumberFormatException e) {
            XDialog.alert("Số bàn và số chỗ ngồi phải là số nguyên!");
            return;
        }

        // Kiểm tra trùng số bàn
        if (tableDAO.findById(tableNumber) != null) {
            XDialog.alert("Số bàn này đã tồn tại! Vui lòng nhập số bàn khác.");
            return;
        }

        // Tạo mới bàn
        TableForCustomer table = new TableForCustomer();
        table.setTable_number(tableNumber);
        table.setAmount(amount);
        table.setStatus(convertStatusToInt(statusText));

        try {
            tableDAO.create(table);
            XDialog.alert("Thêm bàn thành công!");
            loadTable(); // Reload lại để hiển thị bàn mới
            clear();
        } catch (Exception ex) {
            XDialog.alert("Có lỗi xảy ra khi thêm bàn: " + ex.getMessage());
        }
    }

    // Cập nhật phương thức update
    @Override
    public void update() {
        // Lấy thông tin mới từ form
        TableForCustomer newTable = (TableForCustomer) getForm();

        // Lấy thông tin cũ từ DB
        TableForCustomer oldTable = tableDAO.findById(newTable.getTable_number());
        if (oldTable == null) {
            XDialog.alert("Không tìm thấy bàn này trong hệ thống!");
            return;
        }

        // So sánh và tạo thông tin hiển thị
        StringBuilder message = new StringBuilder();
        message.append("Bạn có chắc chắn muốn cập nhật bàn này không?\n\n");
        message.append("THÔNG TIN CŨ:\n");
        message.append("Số bàn: ").append(oldTable.getTable_number()).append("\n");
        message.append("Số chỗ ngồi: ").append(oldTable.getAmount()).append("\n");
        message.append("Trạng thái: ").append(convertIntToStatus(oldTable.getStatus())).append("\n\n");
        message.append("THÔNG TIN MỚI:\n");
        message.append("Số bàn: ").append(newTable.getTable_number()).append("\n");
        message.append("Số chỗ ngồi: ").append(newTable.getAmount()).append("\n");
        message.append("Trạng thái: ").append(convertIntToStatus(newTable.getStatus())).append("\n");

        if (XDialog.confirm(message.toString(), "Xác nhận cập nhật")) {
            try {
                tableDAO.update(newTable);
                XDialog.alert("Cập nhật bàn thành công!");
                loadTable();
                clear();
            } catch (Exception ex) {
                XDialog.alert("Cập nhật bàn thất bại!\n" + ex.getMessage());
            }
        }
        // Nếu chọn "Không" thì không làm gì cả
    }

    // Cập nhật phương thức delete
    @Override
    public void delete() {
        String tableNumberStr = txtTable_Number.getText().trim();

        // 1. Kiểm tra đã nhập số bàn chưa
        if (tableNumberStr.isEmpty()) {
            XDialog.alert("Vui lòng nhập số bàn cần xóa!");
            return;
        }

        int tableNumber;
        try {
            tableNumber = Integer.parseInt(tableNumberStr);
        } catch (NumberFormatException e) {
            XDialog.alert("Số bàn phải là số nguyên!");
            return;
        }

        // 2. Kiểm tra bàn có tồn tại không
        TableForCustomer table = tableDAO.findById(tableNumber);
        if (table == null) {
            XDialog.alert("Không tìm thấy bàn số " + tableNumber + " trong hệ thống!");
            return;
        }

        // 3. Hiển thị thông tin bàn và xác nhận xóa
        StringBuilder message = new StringBuilder();
        message.append("Bạn có chắc chắn muốn xóa bàn này không?\n\n");
        message.append("Số bàn: ").append(table.getTable_number()).append("\n");
        message.append("Số chỗ ngồi: ").append(table.getAmount()).append("\n");
        message.append("Trạng thái: ").append(convertIntToStatus(table.getStatus())).append("\n");

        if (XDialog.confirm(message.toString(), "Xác nhận xóa bàn")) {
            try {
                tableDAO.deleteById(tableNumber);
                XDialog.alert("Xóa bàn thành công!");
                loadTable();
                clear();
            } catch (Exception ex) {
                XDialog.alert("Xóa bàn thất bại!\n" + ex.getMessage());
            }
        }
        // Nếu chọn "Không" thì không làm gì cả
    }

    // Cập nhật phương thức clear
    @Override
    public void clear() {
        try {
            txtTable_Number.setText("");
            txtAmount.setText("");
            cboTable_Status.setSelectedIndex(0);
            XDialog.alert("Làm mới thành công!");
        } catch (Exception ex) {
            XDialog.alert("Làm mới thất bại!\n" + ex.getMessage());
        }
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void changeTable() {
        String currentTableStr = txtTable_Number.getText().trim();
        if (currentTableStr.isEmpty()) {
            XDialog.alert("Vui lòng chọn bàn cần chuyển!");
            return;
        }
        int currentTableNumber;
        try {
            currentTableNumber = Integer.parseInt(currentTableStr);
        } catch (NumberFormatException e) {
            XDialog.alert("Số bàn không hợp lệ!");
            return;
        }

        TableForCustomer currentTable = tableDAO.findById(currentTableNumber);
        if (currentTable == null) {
            XDialog.alert("Không tìm thấy bàn này trong hệ thống!");
            return;
        }

        // Lấy danh sách bàn trống (status = 0, khác bàn hiện tại)
        List<TableForCustomer> allTables = tableDAO.findAll();
        List<TableForCustomer> emptyTables = new java.util.ArrayList<>();
        for (TableForCustomer t : allTables) {
            if (t.getStatus() == 0 && t.getTable_number() != currentTableNumber) {
                emptyTables.add(t);
            }
        }

        if (emptyTables.isEmpty()) {
            XDialog.alert("Không có bàn trống nào để chuyển!\nVui lòng thử lại sau.");
            return;
        }

        // Tạo mảng số bàn để hiển thị cho người dùng chọn
        Integer[] tableNumbers = emptyTables.stream()
                .map(TableForCustomer::getTable_number)
                .toArray(Integer[]::new);

        Integer selectedTableNumber = (Integer) javax.swing.JOptionPane.showInputDialog(
                this,
                "Chọn bàn muốn chuyển sang:",
                "Chuyển bàn",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                tableNumbers,
                tableNumbers[0]
        );

        if (selectedTableNumber == null) {
            // Người dùng bấm Cancel hoặc đóng dialog
            return;
        }

        // Tìm bàn mới được chọn
        TableForCustomer newTable = null;
        for (TableForCustomer t : emptyTables) {
            if (t.getTable_number() == selectedTableNumber) {
                newTable = t;
                break;
            }
        }
        if (newTable == null) {
            XDialog.alert("Không tìm thấy bàn mới để chuyển!");
            return;
        }

        // Xác nhận trước khi chuyển trạng thái
        if (XDialog.confirm(String.format("Bạn có chắc chắn muốn chuyển sang bàn số %d không?", newTable.getTable_number()), "Xác nhận chuyển bàn")) {
            try {
                newTable.setStatus(1); // Đang phục vụ
                currentTable.setStatus(0); // Trống

                tableDAO.update(newTable);
                tableDAO.update(currentTable);

                XDialog.alert(String.format("Chuyển thành công sang bàn số %d!", newTable.getTable_number()));
                loadTable();
                setForm(newTable);
            } catch (Exception ex) {
                XDialog.alert("Chuyển trạng thái bàn thất bại!\n" + ex.getMessage());
            }
        }
        // Nếu chọn "Không" thì không làm gì cả
    }

    private void updateTableStatus(TableForCustomer table, int newStatus) {
        if (XDialog.confirm("Bạn có chắc chắn muốn chuyển trạng thái bàn này không?", "Xác nhận chuyển trạng thái")) {
            try {
                table.setStatus(newStatus);
                tableDAO.update(table);
                XDialog.alert("Chuyển trạng thái bàn thành công!");
                loadTable();
                setForm(table);
            } catch (Exception ex) {
                XDialog.alert("Chuyển trạng thái bàn thất bại!\n" + ex.getMessage());
            }
        }
        // Nếu chọn "Không" thì không làm gì cả
    }
}
