/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team4.quanliquanmicay.View;

import com.team4.quanliquanmicay.Controller.ChangePasswordController;
import com.team4.quanliquanmicay.DAO.UserDAO;
import com.team4.quanliquanmicay.Impl.UserDAOImpl;
import com.team4.quanliquanmicay.util.XAuth;
import com.team4.quanliquanmicay.util.XDialog;
import com.team4.quanliquanmicay.util.XTheme;
import com.team4.quanliquanmicay.util.XValidation;
import javax.swing.text.JTextComponent;
import com.team4.quanliquanmicay.Entity.UserAccount;
import java.awt.Color;
/**
 *
 * @author HP
 */
public class ChangePassword extends javax.swing.JFrame implements ChangePasswordController{

    /**
     * Creates new form PassWord
     */
    public ChangePassword() {
        this.setUndecorated(true); // Ẩn thanh tiêu đề
        XTheme.applyFullTheme();
        initComponents();
        this.setLocationRelativeTo(null);
        addInputListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        txtNewpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtUsername = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(134, 39, 43));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đổi Mật Khẩu");

        jPanel2.setBackground(new java.awt.Color(204, 164, 133));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setIcon(null);
        jLabel2.setText("Tên Tài Khoản :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(null);
        jLabel3.setText("Mật Khẩu Mới :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setIcon(null);
        jLabel4.setText("Xác Nhận Mật Khẩu Mới :");

        txtConfirm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNewpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewpassActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Lưu Thay Đổi");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.save();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (XDialog.confirm("Bạn có chắc chắn muốn thoát khỏi ứng dụng không?", "Xác nhận thoát")) {
         this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtNewpass;
    private javax.swing.JPasswordField txtUsername;
    // End of variables declaration//GEN-END:variables

    
    UserDAO dao = new UserDAOImpl();
 
@Override
public void open() {
 this.setLocationRelativeTo(null);
}
@Override
public void close() {
 this.dispose();
}
@Override
public void save() {
    Color defaultBg = Color.WHITE;
    Color errorBg = new Color(255, 204, 204);

    String username = txtUsername.getText();
    String newpass = txtNewpass.getText();
    String confirm = txtConfirm.getText();

    txtUsername.setBackground(defaultBg);
    txtNewpass.setBackground(defaultBg);
    txtConfirm.setBackground(defaultBg);

    StringBuilder missingFields = new StringBuilder();
    boolean hasError = false;

    if (XValidation.isEmpty(username)) {
        missingFields.append("• Vui lòng điền thông tin tên tài khoản\n");
        setInlineError(txtUsername, "Vui lòng nhập tài khoản", errorBg);
        hasError = true;
    }
    if (XValidation.isEmpty(newpass)) {
        missingFields.append("• Vui lòng điền thông tin mật khẩu mới\n");
        setInlineError(txtNewpass, "Vui lòng nhập mật khẩu", errorBg);
        hasError = true;
    }
    if (XValidation.isEmpty(confirm)) {
        missingFields.append("• Vui lòng điền thông tin xác nhận mật khẩu mới\n");
        setInlineError(txtConfirm, "Vui lòng nhập xác nhận mật khẩu", errorBg);
        hasError = true;
    }

    if (hasError) {
        String errorMessage = "Các trường thông tin bị thiếu:\n" + missingFields.toString();
        XDialog.error(errorMessage, "Thiếu thông tin");
        return;
    }

    if (!newpass.equals(confirm)) {
        XDialog.warning("Xác nhận mật khẩu không đúng!", "Cảnh báo");
        return;
    }
    if (!XValidation.isPassword(newpass)) {
        XDialog.warning("Mật khẩu mới phải tối thiểu 8 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt!", "Cảnh báo");
        txtNewpass.setBackground(errorBg);
        return;
    }
    if (XAuth.user == null) {
        UserAccount user = dao.findByUsername(username.trim());
        if (user == null) {
            XDialog.error("Tên tài khoản không tồn tại!", "Lỗi");
        } else {
            user.setPass(newpass);
            dao.update(user);
            XDialog.success("Đổi mật khẩu thành công!", "Thành công");
            this.close();
        }
    } else {
        if (!username.trim().equalsIgnoreCase(XAuth.user.getUsername().trim())) {
            XDialog.error("Sai tên tài khoản!", "Lỗi");
        } else {
            XAuth.user.setPass(newpass);
            dao.update(XAuth.user);
            XDialog.success("Đổi mật khẩu thành công!", "Thành công");
            this.close();
        }
    }
}

private void addInputListeners() {
    Color defaultBg = Color.WHITE;
    attachFieldHandlers(txtUsername, defaultBg);
    attachFieldHandlers(txtNewpass, defaultBg);
    attachFieldHandlers(txtConfirm, defaultBg);
}

private void setInlineError(JTextComponent field, String message, Color errorBg) {
    field.setBackground(errorBg);
    field.setForeground(new java.awt.Color(102, 0, 0));
    // Với JPasswordField: tắt echoChar để hiện thông báo thay vì dấu chấm
    if (field instanceof javax.swing.JPasswordField) {
        javax.swing.JPasswordField pf = (javax.swing.JPasswordField) field;
        if (field.getClientProperty("defaultEchoChar") == null) {
            field.putClientProperty("defaultEchoChar", Character.valueOf(pf.getEchoChar()));
        }
        pf.setEchoChar((char) 0);
    }
    field.setText(message);
    field.putClientProperty("inlineError", Boolean.TRUE);
}

private void attachFieldHandlers(JTextComponent field, Color defaultBg) {
    final java.awt.Color defaultFg = field.getForeground();
    field.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            Object flag = field.getClientProperty("inlineError");
            if (Boolean.TRUE.equals(flag)) {
                field.setText("");
                field.putClientProperty("inlineError", Boolean.FALSE);
                // Khôi phục echoChar cho JPasswordField khi người dùng bắt đầu nhập
                if (field instanceof javax.swing.JPasswordField) {
                    javax.swing.JPasswordField pf = (javax.swing.JPasswordField) field;
                    Object ch = field.getClientProperty("defaultEchoChar");
                    if (ch instanceof Character) {
                        pf.setEchoChar(((Character) ch).charValue());
                    }
                }
            }
            field.setBackground(defaultBg);
            field.setForeground(defaultFg);
        }
    });
    field.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent e) {
            if (!field.getText().trim().isEmpty()) {
                field.setBackground(defaultBg);
                field.setForeground(defaultFg);
                // Nếu còn cờ inlineError thì hủy và khôi phục echoChar
                if (Boolean.TRUE.equals(field.getClientProperty("inlineError"))) {
                    field.putClientProperty("inlineError", Boolean.FALSE);
                    if (field instanceof javax.swing.JPasswordField) {
                        javax.swing.JPasswordField pf = (javax.swing.JPasswordField) field;
                        Object ch = field.getClientProperty("defaultEchoChar");
                        if (ch instanceof Character) {
                            pf.setEchoChar(((Character) ch).charValue());
                        }
                    }
                }
            }
        }
    });
}
}
