/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team4.quanliquanmicay.View;

import com.team4.quanliquanmicay.util.XTheme;
import com.team4.quanliquanmicay.util.XDialog;

import com.team4.quanliquanmicay.DAO.TableForCustomerDAO;
import com.team4.quanliquanmicay.Entity.TableForCustomer;
import com.team4.quanliquanmicay.Impl.TableForCustomerDAOImpl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.border.LineBorder;
import javax.swing.border.CompoundBorder;
import java.awt.GridLayout;
import com.team4.quanliquanmicay.View.BillUI;


/**
 *
 * @author Asus
 */
public class ChooseTableUI extends javax.swing.JFrame {

    /**
     * Creates new form ChooseTable
     */
    public ChooseTableUI() {
        this.setUndecorated(true);
        XTheme.applyFullTheme();
        initComponents();
        
        // Xóa các dòng ép buộc kích thước cố định
        // XÓA hoặc COMMENT các dòng dưới đây để dùng đúng layout, size, ... của .form

        // this.setSize(800, 600);
        // this.setPreferredSize(new java.awt.Dimension(800, 600));
        // this.setMaximumSize(new java.awt.Dimension(800, 600));
        // this.setMinimumSize(new java.awt.Dimension(800, 600));
        
        this.setLocationRelativeTo(null);
        
        // Đặt tab 1-12 làm tab mặc định
        pnlTable.setSelectedIndex(0);
        
        // Xóa các dòng ép buộc kích thước button
        // ÉP BUỘC KÍCH THƯỚC KHÁC NHAU CHO HAI NÚT
        // jButton1.setPreferredSize(new java.awt.Dimension(350, 50));
        // jButton1.setMinimumSize(new java.awt.Dimension(350, 50));
        // jButton1.setMaximumSize(new java.awt.Dimension(350, 50));
        
        // jButton2.setPreferredSize(new java.awt.Dimension(200, 50));
        // jButton2.setMinimumSize(new java.awt.Dimension(200, 50));
        // jButton2.setMaximumSize(new java.awt.Dimension(200, 50));
        
        // Thêm dòng này để fill dữ liệu khi mở form
        loadTable();
        
        // Thêm event listener cho các button
        btnTranferTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
  
        // Đảm bảo giao diện hiển thị đúng theo thiết kế
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnlTable = new javax.swing.JTabbedPane();
        pnlTable1to12 = new javax.swing.JPanel();
        pnlTable13to24 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnTranferTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitle.setBackground(new java.awt.Color(134, 39, 43));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("CHỌN BÀN");

        jPanel5.setBackground(new java.awt.Color(204, 164, 133));

        pnlTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlTable1to12Layout = new javax.swing.GroupLayout(pnlTable1to12);
        pnlTable1to12.setLayout(pnlTable1to12Layout);
        pnlTable1to12Layout.setHorizontalGroup(
            pnlTable1to12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTable1to12Layout.setVerticalGroup(
            pnlTable1to12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlTable.addTab("1-12", pnlTable1to12);

        javax.swing.GroupLayout pnlTable13to24Layout = new javax.swing.GroupLayout(pnlTable13to24);
        pnlTable13to24.setLayout(pnlTable13to24Layout);
        pnlTable13to24Layout.setHorizontalGroup(
            pnlTable13to24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTable13to24Layout.setVerticalGroup(
            pnlTable13to24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlTable.addTab("13-24", pnlTable13to24);

        btnExit.setBackground(new java.awt.Color(119, 50, 5));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_and_images/icon/Exit.png"))); // NOI18N
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        btnTranferTable.setBackground(new java.awt.Color(204, 255, 204));
        btnTranferTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTranferTable.setForeground(new java.awt.Color(0, 153, 0));
        btnTranferTable.setText("Chuyển bàn");
        btnTranferTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTable)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(btnTranferTable, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTranferTable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Thêm các biến sau vào class ChooseTableUI
    private TableForCustomerDAO tableDAO = new TableForCustomerDAOImpl();
    private JButton selectedButton = null;
    private int selectedTableNumber = -1;
    // Thêm biến để theo dõi double click
    private long lastClickTime = 0;
    private JButton lastClickedButton = null;
    private static final long DOUBLE_CLICK_TIME = 300; // milliseconds
    
    // Thêm biến để theo dõi BillUI
    private BillUI currentBillUI = null;

    // XÓA HOÀN TOÀN hàm openHoaDonDialog cũ ở dòng 559-572
    // CHỈ GIỮ LẠI hàm này
    /**
     * Mở BillUI với thông tin bàn đã chọn
     */
    private void openHoaDonDialog(int tableNumber) {
        try {
            // Kiểm tra trạng thái bàn trước khi mở
            TableForCustomer table = tableDAO.findById(tableNumber);
            if (table == null) {
                XDialog.alert("Không tìm thấy thông tin bàn!", "Lỗi");
                return;
            }
            
            // Tạo BillUI mới
            currentBillUI = new BillUI();
            
            // Set thông tin bàn vào dialog
            currentBillUI.setTableInfo(tableNumber);
            
            // COMMENT DÒNG NÀY VÌ BillUI CHƯA CÓ METHOD setTableStatusCallback
            // TODO: Cần thêm method này vào BillUI để callback hoạt động
            // currentBillUI.setTableStatusCallback(new TableStatusCallback() {
            //     @Override
            //     public void onItemAdded(int tableNum) {
            //         // Khi có món được thêm, cập nhật trạng thái bàn thành "đang hoạt động"
            //         updateTableStatusToActive(tableNum);
            //     }
            //     
            //     @Override
            //     public void onBillPaid(int tableNum) {
            //         // Khi thanh toán xong, cập nhật trạng thái bàn thành "trống"
            //         updateTableStatusToEmpty(tableNum);
            //     }
            // });
            
            // Thêm listener để xử lý khi BillUI đóng
            currentBillUI.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    handleBillUIClosed(tableNumber, table);
                }
            });
            
            // Ẩn ChooseTableUI
            this.setVisible(false);
            
            // Hiển thị BillUI
            currentBillUI.setVisible(true);
            
        } catch (Exception e) {
            System.err.println("Lỗi khi mở HoaDonJDialog: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // THÊM MỚI: Interface callback để BillUI có thể thông báo về thay đổi
    public interface TableStatusCallback {
        void onItemAdded(int tableNumber);
        void onBillPaid(int tableNumber);
    }

    // THÊM MỚI: Cập nhật trạng thái bàn thành "đang hoạt động" khi có món được thêm
    public void updateTableStatusToActive(int tableNumber) {
        try {
            TableForCustomer table = tableDAO.findById(tableNumber);
            if (table != null && table.getStatus() != 1) {
                table.setStatus(1); // Đang hoạt động
                tableDAO.update(table);
                System.out.println("✅ Cập nhật trạng thái bàn " + tableNumber + " thành ĐANG HOẠT ĐỘNG (có món được thêm)");
                
                // Cập nhật giao diện nếu ChooseTableUI đang hiển thị
                if (this.isVisible()) {
                    loadTable();
                }
            }
        } catch (Exception e) {
            System.err.println("Lỗi khi cập nhật trạng thái bàn thành đang hoạt động: " + e.getMessage());
        }
    }

    // THÊM MỚI: Cập nhật trạng thái bàn thành "trống" khi thanh toán xong
    public void updateTableStatusToEmpty(int tableNumber) {
        try {
            TableForCustomer table = tableDAO.findById(tableNumber);
            if (table != null && table.getStatus() != 0) {
                table.setStatus(0); // Trống
                tableDAO.update(table);
                System.out.println("✅ Cập nhật trạng thái bàn " + tableNumber + " thành TRỐNG (đã thanh toán)");
                
                // Cập nhật giao diện nếu ChooseTableUI đang hiển thị
                if (this.isVisible()) {
                    loadTable();
                }
            }
        } catch (Exception e) {
            System.err.println("Lỗi khi cập nhật trạng thái bàn thành trống: " + e.getMessage());
        }
    }

    // Sửa lại hàm handleBillUIClosed để chỉ cập nhật khi thực sự cần thiết
    private void handleBillUIClosed(int tableNumber, TableForCustomer originalTable) {
        try {
            // Kiểm tra lại trạng thái bàn sau khi BillUI đóng
            TableForCustomer currentTable = tableDAO.findById(tableNumber);
            if (currentTable == null) {
                System.err.println("Không tìm thấy bàn sau khi BillUI đóng");
                return;
            }
            
            // Kiểm tra xem có bill nào đang hoạt động VÀ có đồ ăn/đồ uống không
            boolean hasActiveBillWithItems = checkIfTableHasActiveBillWithItems(tableNumber);
            
            if (hasActiveBillWithItems) {
                // Có bill đang hoạt động VÀ có đồ ăn/đồ uống - đảm bảo trạng thái bàn là "đang hoạt động"
                if (currentTable.getStatus() != 1) {
                    currentTable.setStatus(1);
                    tableDAO.update(currentTable);
                    System.out.println("🔄 Sync: Cập nhật trạng thái bàn " + tableNumber + " thành đang hoạt động");
                }
            } else {
                // Không có bill hoặc bill không có đồ ăn/đồ uống - đảm bảo trạng thái bàn là "trống"
                if (currentTable.getStatus() != 0) {
                    currentTable.setStatus(0);
                    tableDAO.update(currentTable);
                    System.out.println("🔄 Sync: Cập nhật trạng thái bàn " + tableNumber + " thành trống");
                }
            }
            
            // Cập nhật giao diện bàn
            loadTable();
            
            // Hiển thị lại ChooseTableUI chỉ khi KHÔNG có PayUI nào đang mở
            if (!isAnyPayUIVisible()) {
                this.setVisible(true);
            }
            
        } catch (Exception e) {
            System.err.println("Lỗi khi xử lý BillUI đóng: " + e.getMessage());
            // Chỉ hiển thị lại khi không có PayUI
            if (!isAnyPayUIVisible()) {
                this.setVisible(true);
            }
        }
    }

    // Kiểm tra có PayUI nào đang hiển thị không
    private boolean isAnyPayUIVisible() {
        for (Window w : Window.getWindows()) {
            if (w instanceof com.team4.quanliquanmicay.View.PayUI && w.isShowing()) {
                return true;
            }
        }
        return false;
    }

    // Sửa lại hàm checkIfTableHasActiveBillWithItems để xử lý lỗi ORA-01722
    private boolean checkIfTableHasActiveBillWithItems(int tableNumber) {
        try {
            // Thử với status dưới dạng string trước
            String billSql = "SELECT bill_id FROM BILL WHERE table_number = ? AND status = '0'";
            String billIdStr = com.team4.quanliquanmicay.util.XJdbc.executeQuery(billSql, rs -> {
                if (rs.next()) {
                    return rs.getString("bill_id");
                }
                return null;
            }, tableNumber);
            
            if (billIdStr == null || billIdStr.trim().isEmpty()) {
                // Không có bill đang hoạt động
                System.out.println("Bàn " + tableNumber + " - Không có bill đang hoạt động");
                return false;
            }
            
            // Chuyển đổi bill_id từ String sang Integer một cách an toàn
            Integer billId;
            try {
                billId = Integer.parseInt(billIdStr.trim());
            } catch (NumberFormatException e) {
                System.err.println("Lỗi chuyển đổi bill_id: " + billIdStr + " - " + e.getMessage());
                return false;
            }
            
            // Kiểm tra xem bill này có đồ ăn/đồ uống không
            Integer itemCount = null;
            try {
                final String ITEMS_TABLE = "BILL_DETAIL"; // Tên bảng đúng theo DAO
                String itemsSql = "SELECT COUNT(*) FROM " + ITEMS_TABLE + " WHERE bill_id = ?";
                itemCount = com.team4.quanliquanmicay.util.XJdbc.executeQuery(itemsSql, rs -> {
                    if (rs.next()) {
                        return rs.getInt(1);
                    }
                    return 0;
                }, billId);
            } catch (Exception ex) {
                String msg = ex.getMessage();
                if (msg != null && msg.contains("ORA-00942")) {
                    // Bảng chi tiết không tồn tại trong schema hiện tại → coi như 0 món để tránh crash
                    System.err.println("[WARN] Thiếu bảng BILL_DETAIL. Bỏ qua đếm món và xem như 0 món.");
                    itemCount = 0;
                } else {
                    throw ex;
                }
            }

            // Chỉ trả về true nếu có bill đang hoạt động VÀ có ít nhất 1 món
            boolean hasItems = itemCount != null && itemCount > 0;
            System.out.println("Bàn " + tableNumber + " - Bill ID: " + billId + " - Số món: " + itemCount + " - Có đồ ăn: " + hasItems);

            return hasItems;
            
        } catch (Exception e) {
            System.err.println("Lỗi khi kiểm tra bill: " + e.getMessage());
            e.printStackTrace();
            
            // Fallback: kiểm tra đơn giản hơn
            return checkIfTableHasActiveBillSimple(tableNumber);
        }
    }

    // THÊM MỚI: Hàm fallback để kiểm tra đơn giản hơn
    private boolean checkIfTableHasActiveBillSimple(int tableNumber) {
        try {
            // Kiểm tra đơn giản: chỉ xem có bill nào của bàn này không
            String simpleSql = "SELECT COUNT(*) FROM BILL WHERE table_number = ?";
            Integer billCount = com.team4.quanliquanmicay.util.XJdbc.executeQuery(simpleSql, rs -> {
                if (rs.next()) {
                    return rs.getInt(1);
                }
                return 0;
            }, tableNumber);
             
            boolean hasBill = billCount != null && billCount > 0;
            System.out.println("Bàn " + tableNumber + " - Fallback check: Có " + billCount + " bill");
            
            return hasBill;
            
        } catch (Exception e) {
            System.err.println("Lỗi fallback check: " + e.getMessage());
            return false;
        }
    }

    // Hàm fill dữ liệu bàn lên 2 panel
    public void loadTable() {
        List<TableForCustomer> tables = tableDAO.findAll();
        pnlTable1to12.removeAll();
        pnlTable13to24.removeAll();

        // PHẢI set layout cho panel để add button động!
        pnlTable1to12.setLayout(new GridLayout(2, 6, 15, 15));
        pnlTable13to24.setLayout(new GridLayout(2, 6, 15, 15));

        // Tạo map để tra cứu nhanh
        java.util.Map<Integer, TableForCustomer> tableMap = new java.util.HashMap<>();
        for (TableForCustomer t : tables) {
            tableMap.put(t.getTable_number(), t);
        }

        // 1-12: Normal
        for (int i = 1; i <= 12; i++) {
            TableForCustomer table = tableMap.get(i);
            JButton btn = createButton(i, table);
            btn.setMaximumSize(new Dimension(120, 800));
            btn.setPreferredSize(new Dimension(120, 800));
            pnlTable1to12.add(btn);
        }

        // 13-24: VIP
        for (int i = 13; i <= 24; i++) {
            TableForCustomer table = tableMap.get(i);
            JButton btn = createButton(i, table);
            btn.setMaximumSize(new Dimension(120, 100));
            btn.setPreferredSize(new Dimension(120, 100));
            pnlTable13to24.add(btn);
        }

        // Cập nhật giao diện
        pnlTable1to12.revalidate();
        pnlTable1to12.repaint();
        pnlTable13to24.revalidate();
        pnlTable13to24.repaint();
    }

    // Hàm tạo button cho từng bàn
    private JButton createButton(int tableNumber, TableForCustomer table) {
        JButton btnTable = new JButton();
        btnTable.setContentAreaFilled(false);
        btnTable.setOpaque(true);
        btnTable.setText(String.format("#%d", tableNumber));
        btnTable.setPreferredSize(new Dimension(120, 100)); // <-- Thêm dòng này để set height 100px
        btnTable.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 22));
        btnTable.setOpaque(true);
        btnTable.setContentAreaFilled(true);
        btnTable.setBorderPainted(false);
        btnTable.setFocusPainted(false);

        final int buttonStatus = (table != null) ? table.getStatus() : -1;

        if (table == null) {
            btnTable.setEnabled(false);
            btnTable.setBackground(new Color(120, 144, 156));
        } else {
            // Kiểm tra nếu bàn ngưng hoạt động
            if (buttonStatus == 2) {
                btnTable.setEnabled(false);
                btnTable.setBackground(getBaseColorByStatus(buttonStatus));
                btnTable.setToolTipText("Bàn này tạm ngưng hoạt động");
            } else {
                btnTable.setEnabled(true);
                btnTable.setBorder(javax.swing.BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2));
                btnTable.setBorderPainted(true);
                
                // Set màu ban đầu theo TableManagement
                btnTable.setBackground(getBaseColorByStatus(buttonStatus));
                
                btnTable.setActionCommand(String.valueOf(table.getTable_number()));
                
                // Thêm MouseListener để xử lý click và hover
                btnTable.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        if (btnTable.isEnabled()) {
                            btnTable.setBackground(getHoverColorByStatus(buttonStatus));
                            btnTable.repaint();
                        }
                    }
                    
                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        if (btnTable.isEnabled()) {
                            if (btnTable == selectedButton) {
                                btnTable.setBackground(getSelectedColorByStatus(buttonStatus));
                            } else {
                                btnTable.setBackground(getBaseColorByStatus(buttonStatus));
                            }
                            btnTable.repaint();
                        }
                    }
                    
                    @Override
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        if (btnTable.isEnabled()) {
                            // Thay đổi từ màu đen thành màu tối hơn của chính button đó
                            btnTable.setBackground(getPressedColorByStatus(buttonStatus));
                            btnTable.repaint();
                        }
                    }
                    
                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        if (btnTable.isEnabled()) {
                            long currentTime = System.currentTimeMillis();
                            
                            // Kiểm tra xem có phải double click vào cùng button không
                            if (currentTime - lastClickTime < DOUBLE_CLICK_TIME && 
                                lastClickedButton == btnTable) {
                                // Double click vào cùng button - mở BillUI
                                int num = Integer.parseInt(btnTable.getActionCommand());
                                 
                                // Kiểm tra trạng thái bàn trước khi mở
                                TableForCustomer table = tableDAO.findById(num);
                                if (table != null) {
                                    // Chỉ cho phép mở BillUI nếu bàn không ngưng hoạt động
                                    if (table.getStatus() != 2) {
                                        openHoaDonDialog(num);
                                    } else {
                                        XDialog.alert("Bàn này tạm ngưng hoạt động!", "Thông báo");
                                    }
                                }
                            } else {
                                // Single click hoặc click vào button khác - chỉ chọn bàn
                                int num = Integer.parseInt(btnTable.getActionCommand());
                                selectTable(num, btnTable);
                            }
                            
                            // Cập nhật thông tin click cuối cùng
                            lastClickTime = currentTime;
                            lastClickedButton = btnTable;
                            
                            // Reset màu sau khi click
                            if (btnTable == selectedButton) {
                                btnTable.setBackground(getSelectedColorByStatus(buttonStatus));
                            } else {
                                btnTable.setBackground(getBaseColorByStatus(buttonStatus));
                            }
                            btnTable.repaint();
                        }
                    }
                });
            }
        }
        return btnTable;
    }

    // Cập nhật các hàm màu theo yêu cầu cụ thể
    private Color getBaseColorByStatus(int status) {
        switch (status) {
            case 0: return Color.decode("#CCCCCC"); // Trống - xám nhạt
            case 1: return Color.decode("#D6F5D6"); // Đang hoạt động - xanh nhạt
            case 2: return Color.decode("#FFCCCC"); // Ngưng hoạt động - đỏ nhạt
            default: return Color.GRAY;
        }
    }
    
    private Color brightenColor(Color color, float factor) {
        int r = Math.min(255, (int)(color.getRed() + (255 - color.getRed()) * factor));
        int g = Math.min(255, (int)(color.getGreen() + (255 - color.getGreen()) * factor));
        int b = Math.min(255, (int)(color.getBlue() + (255 - color.getBlue()) * factor));
        return new Color(r, g, b);
    }
    
    private Color darkenColor(Color color, float factor) {
        int r = Math.max(0, (int)(color.getRed() * (1 - factor)));
        int g = Math.max(0, (int)(color.getGreen() * (1 - factor)));
        int b = Math.max(0, (int)(color.getBlue() * (1 - factor)));
        return new Color(r, g, b);
    }
    
    // Hover: màu khi đưa chuột tới
    private Color getHoverColorByStatus(int status) {
        switch (status) {
            case 0: return Color.decode("#999999"); // Trống - xám đậm hơn
            case 1: return Color.decode("#ADEBAD"); // Đang hoạt động - xanh đậm hơn
            case 2: return Color.decode("#990000"); // Ngưng hoạt động - đỏ đậm
            default: return Color.GRAY;
        }
    }
    
    // Chọn: màu khi được nhấp vào
    private Color getSelectedColorByStatus(int status) {
        switch (status) {
            case 0: return Color.decode("#666666"); // Trống - xám đậm nhất
            case 1: return Color.decode("#85E085"); // Đang hoạt động - xanh đậm nhất
            case 2: return Color.decode("#660000"); // Ngưng hoạt động - đỏ đậm pha nâu
            default: return Color.GRAY;
        }
    }
    
    // Nhấn chuột: màu khi bấm giữ
    private Color getPressedColorByStatus(int status) {
        return darkenColor(getBaseColorByStatus(status), 0.30f);
    }

    // Hàm chọn bàn (chỉ thay đổi màu và border, không mở BillUI)
    private void selectTable(int tableNumber, JButton btnTable) {
        // Đổi border và màu button cũ về mặc định
        if (selectedButton != null && selectedButton != btnTable) {
            selectedButton.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 2));
            selectedButton.setBorderPainted(true);
            TableForCustomer oldTable = tableDAO.findById(selectedTableNumber);
            if (oldTable != null) {
                selectedButton.setBackground(getBaseColorByStatus(oldTable.getStatus()));
            }
        }

        // Đặt border giống TableManagement: màu xám đậm dày 2px + viền trắng 2px
        btnTable.setBorder(new CompoundBorder(
            new LineBorder(Color.decode("#424242"), 2, true),
            new LineBorder(Color.WHITE, 2)
        ));
        btnTable.setBorderPainted(true);

        // Đổi màu nền button được chọn thành màu đậm nhất theo status
        TableForCustomer table = tableDAO.findById(tableNumber);
        if (table != null) {
            btnTable.setBackground(getSelectedColorByStatus(table.getStatus()));
        }

        selectedButton = btnTable;
        selectedTableNumber = tableNumber;
    }
    
    /**
     * Mở BillUI với thông tin bàn đã chọn
     */

    // Event handlers cho các button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Xử lý sự kiện cho button "Chuyển bàn"
        if (selectedTableNumber != -1) {
            // Kiểm tra trạng thái bàn được chọn
            TableForCustomer selectedTable = tableDAO.findById(selectedTableNumber);
            if (selectedTable == null) {
                XDialog.alert("Không tìm thấy thông tin bàn!", "Lỗi");
                return;
            }
            
            // Kiểm tra xem bàn có phải bàn ngưng hoạt động không
            if (selectedTable.getStatus() == 2) {
                XDialog.alert("Bàn này tạm ngưng hoạt động!", "Thông báo");
                return;
            }

            // Kiểm tra xem bàn có phải bàn trống không
            if (selectedTable.getStatus() == 0) {
                XDialog.alert("Chỉ có thể chuyển bàn đang hoạt động!", "Thông báo");
                return;
            }
            
            // Chỉ cho phép chuyển bàn đang hoạt động (status = 1)
            if (selectedTable.getStatus() == 1) {
                // Mở UI chuyển bàn
                openTransferTableDialog();
            } else {
                XDialog.alert("Bàn này không thể chuyển!", "Thông báo");
            }
        } else {
            // Hiển thị thông báo chưa chọn bàn
            XDialog.alert("Vui lòng chọn bàn trước khi chuyển!", "Thông báo");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Xử lý sự kiện cho button Exit với xác nhận
        if (XDialog.confirm("Bạn có chắc chắn muốn thoát khỏi ứng dụng?", "Xác nhận thoát")) {
            this.dispose();
        }
        // Nếu chọn NO thì không làm gì cả, tiếp tục sử dụng ứng dụng
    }
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
        // Xử lý sự kiện cho button Exit với xác nhận
        if (XDialog.confirm("Bạn có chắc chắn muốn thoát khỏi ứng dụng?", "Xác nhận thoát")) {
            this.dispose();
        }
        // Nếu chọn NO thì không làm gì cả, tiếp tục sử dụng ứng dụng
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseTableUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTranferTable;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTabbedPane pnlTable;
    private javax.swing.JPanel pnlTable13to24;
    private javax.swing.JPanel pnlTable1to12;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * Mở dialog chuyển bàn
     */
    private void openTransferTableDialog() {
        try {
            // Tạo dialog chuyển bàn
            TransferTableUI transferDialog = new TransferTableUI(this, selectedTableNumber);
            transferDialog.setVisible(true);
        } catch (Exception e) {
            System.err.println("Lỗi khi mở dialog chuyển bàn: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
