package com.team4.quanliquanmicay.View;


import com.team4.quanliquanmicay.Controller.WelcomeCotroller;
import com.team4.quanliquanmicay.util.XTheme;
import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.plaf.basic.BasicProgressBarUI;
import javax.swing.JComponent;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.FontMetrics;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author HP
 */
public class Welcome extends javax.swing.JFrame implements WelcomeCotroller{

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        this.setUndecorated(true); // Ẩn thanh tiêu đề
        XTheme.applyFullTheme();
        initComponents();
        this.setLocationRelativeTo(null);

        // Cấu hình progress bar
        progressBar.setBackground(new java.awt.Color(240, 240, 240));
        progressBar.setForeground(new java.awt.Color(134, 39, 43));
        progressBar.setStringPainted(true);
        progressBar.setString("0%");
        progressBar.setFont(new java.awt.Font("Segoe UI", 1, 16));
        progressBar.setPreferredSize(new java.awt.Dimension(600, 35));
        progressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 39, 43), 2));

        // Ép màu text ban đầu
        SwingUtilities.invokeLater(() -> {
            UIManager.put("ProgressBar.selectionForeground", new Color(134, 39, 43));
            UIManager.put("ProgressBar.selectionBackground", new Color(134, 39, 43));
            progressBar.updateUI();
            progressBar.setForeground(new Color(134, 39, 43));
        });

        SwingUtilities.invokeLater(() -> {
            com.team4.quanliquanmicay.util.XImage.setImageToLabel(jLabel4, "/icons_and_images/icon/Welcome.jpg");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(194, 154, 123));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 164, 133));

        jPanel2.setBackground(new java.awt.Color(134, 39, 43));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WELCOME TO FIVEC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel3)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("\"Cay không chỉ ở vị, mà còn ở cách sống.\"");

        progressBar.setBackground(new java.awt.Color(240, 240, 240));
        progressBar.setForeground(new java.awt.Color(134, 39, 43));
        progressBar.setStringPainted(true);
        progressBar.setString("0%");
        progressBar.setFont(new java.awt.Font("Segoe UI", 1, 16));
        progressBar.setPreferredSize(new java.awt.Dimension(600, 35));
        progressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 39, 43), 2));

        // Tùy chỉnh UI để ép cập nhật màu text
        progressBar.setUI(new javax.swing.plaf.basic.BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(Graphics g, JComponent c) {
                // Vẽ background
                g.setColor(progressBar.getBackground());
                g.fillRect(0, 0, progressBar.getWidth(), progressBar.getHeight());
                
                // Vẽ thanh progress
                g.setColor(new Color(134, 39, 43));
                int width = (int)((double)progressBar.getValue() / progressBar.getMaximum() * progressBar.getWidth());
                g.fillRect(0, 0, width, progressBar.getHeight());
                
                // Vẽ text với màu tùy chỉnh
                if (progressBar.isStringPainted()) {
                    Graphics2D g2d = (Graphics2D) g.create();
                    g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                    
                    String progressString = progressBar.getString();
                    g2d.setFont(progressBar.getFont());
                    FontMetrics fm = g2d.getFontMetrics();
                    
                    int stringWidth = fm.stringWidth(progressString);
                    int stringHeight = fm.getHeight();
                    
                    int x = (progressBar.getWidth() - stringWidth) / 2;
                    int y = (progressBar.getHeight() - stringHeight) / 2 + fm.getAscent();
                    
                    // Set màu text dựa vào giá trị progress
                    if (progressBar.getValue() >= 50) {
                        g2d.setColor(Color.WHITE);
                    } else {
                        g2d.setColor(new Color(134, 39, 43));
                    }
                    
                    g2d.drawString(progressString, x, y);
                    g2d.dispose();
                }
            }
        });

        // Thêm listener để cập nhật khi giá trị thay đổi
        progressBar.addChangeListener(e -> progressBar.repaint());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(147, 147, 147))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
waiting();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void waiting() {
        this.setLocationRelativeTo(null);
        new Thread(() -> {
            try {
                // Tính toán thời gian delay để chạy trong 3 giây
                int totalSteps = 100;
                int totalTimeMs = 3000; // 3 giây
                int delayMs = totalTimeMs / totalSteps; // 30ms mỗi bước
                
                for (var i = 0; i <= 100; i++) {
                    final int value = i;
                    SwingUtilities.invokeLater(() -> {
                        progressBar.setValue(value);
                        progressBar.setString(value + "%");
                        
                        // Ép màu text
                        if (value >= 50) {
                            UIManager.put("ProgressBar.selectionForeground", Color.WHITE);
     
                        } else {
                            UIManager.put("ProgressBar.selectionForeground", new Color(134, 39, 43));
                            progressBar.setForeground(new Color(134, 39, 43));
                        }
                        progressBar.updateUI();
                    });
                    Thread.sleep(delayMs);
                }
                
                // Sau khi hoàn thành, đóng Welcome và mở Login
                SwingUtilities.invokeLater(() -> {
                    Welcome.this.dispose();
                    new Login().setVisible(true);
                });
                
            } catch (InterruptedException ex) {
                System.exit(0);
            }
        }).start();
    }
}
